[project]
name = "pixi_ros_template"
version = "0.1.0"
description = "A template pixi ros environment"
authors = [
    "Austin Gregg-Smith <blooop@gmail.com>",
    "Ruben Arts <ruben.arts@hotmail.com>",
]
channels = ["conda-forge", "robostack-humble"]
platforms = ["linux-64"]

# ROS workspace activation
[target.unix.activation]
scripts = [".pixi/install/setup.sh"]

[tasks]
#General Workspace tasks for all projects

vcs = "vcs import . < depend.repos"
rosdep-init = { cmd = "rosdep init || true && rosdep update" }
rosdep = { cmd = "rosdep install --from-paths . --ignore-src -r -y", depends-on = [
    "rosdep-init",
] }
setup = { depends-on = ["vcs", "rosdep"] }

ci = { cmd = "echo ci has passed!", depends-on = ["lint", "test"] }
build = "colcon build --build-base .pixi/build --install-base .pixi/install --symlink-install"
clean = "colcon clean workspace -y --build-base .pixi/build --install-base .pixi/install"
test = { cmd = "colcon test --build-base .pixi/build --install-base .pixi/install", depends-on = "build" }
lint = "pre-commit run --all-files"
fix-commit-push = { cmd = "git commit -am 'applied pre-commit'; git push", depends-on = [
    "lint",
] }

#Custom tasks for this project
#add them here

[dependencies]
ros-humble-desktop = "0.10.0.*"
ros-humble-ament-cmake-auto = "*"

colcon-core = "*"
colcon-ros = "*"

# Limit setup tools to avoid deprecation warning. https://answers.ros.org/question/396439/setuptoolsdeprecationwarning-setuppy-install-is-deprecated-use-build-and-pip-and-other-standards-based-tools/
setuptools = "<=58.2.0"

# Needed to get the correct compiled result including the RPATH set for the conda environment lib folder.
compilers = "1.6.0.*"
pkg-config = "0.29.2.*"
cmake = "3.25.2.*"
ros-humble-ament-cmake-gtest = ">=1.3.2,<2"
pytest = "<7"
pre-commit = "*"
gcc = "*"
rosdep = "*"

[pypi-dependencies]
colcon-clean = "*"
vcstool = "*"
